### ISSUE TITLE
How do I display multiple API health statuses

### ISSUE THREAD

**Issue by NedimHodzic** [webscopeio/react-health-check#405] opened 2022-08-10 20:13 UTC
I am trying to display more than one API health status. I downloaded the repo and worked in the example global config, I found a way to do it in here by making a new file for each API I have, I was wondering if there was a better way to do this than making new files. I have also been trying to do it in my own app that I created with npx create-react-app. I tried doing it like I did before but it was not working and it kept saying "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'url')" in the console. I would really like to know how to do it both ways so if anyone can help I would really appreciate it!

**Comment by jozefhruska** [comment] 2022-08-15 06:58
Hi @NedimHodzic,

I've put together a [sandbox with multiple services](https://codesandbox.io/s/suspicious-gwen-4y0i5o?file=/src/App.js), and everything seems to be working just fine. If you open the application in a new window, you can see network requests are being fired against both services.

Please ensure you are correctly configuring the services in the global config (`HealthCheckConfig`) or directly in the `useHealthCheck` hook.

If this won't help you resolve your issue, send me a reproducible example, and I'll try my best to help you out 🙂

**Comment by NedimHodzic** [comment] 2022-08-15 21:21
Sorry for the late reply! I will try this and let you know. I think this
should work though.
Thank you so much for the help!

**Comment by jozefhruska** [comment] 2022-08-19 10:09
@NedimHodzic Have you resolved your issue? Can I close this? Let me know if you need help 🙂

**Comment by NedimHodzic** [comment] 2022-08-20 00:13
Yep its resolved, feel free to close it. Thank you!

**Closed as completed** 2022-08-20 06:56 UTC
Labels: question
